In [1]:
import numpy as np

In [9]:
print("Version:", np.__version__)
print"Configuration:")
np.show_config()

Version: 1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('H

In [8]:
vec1 = np.zeros(10)
print(vec1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
print(vec1.size)

10

In [10]:
vec2 = np.zeros(10)
vec2[4] = 1
print(vec2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
vec3 = np.arange(10, 50)
print(vec3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
vec3 = vec3[::-1]
print(vec3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
matrix1 = np.arange(9)
matrix2 = matrix.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
vec4 = [1, 2, 0, 0, 4, 0]
print(np.nonzero(vec4))


(array([0, 1, 4]),)


In [27]:
matrix2 = np.eye(3)
print(matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
matrix3 = np.random.randint(size = (3, 3, 3))
print(matrix3)

TypeError: randint() takes at least 1 positional argument (0 given)

In [33]:
matrix4 = np.random.randint(5, size = (10, 10))
print(matrix4.min(), matrix4.max())

0 4


In [22]:
vec5 = np.random.randint(1, 10, 30)
print(vec5)
print(vec5.mean())

[1 9 3 1 5 6 5 1 5 4 6 8 6 8 6 5 1 9 7 8 8 2 3 5 3 8 1 2 5 1]
4.733333333333333


In [26]:
matrix4 = np.ones((10, 10), int)
matrix4[1:-1, 1:-1] = 0
print(matrix4)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
